export const GET_PROMOTIONS_REQUEST = 'GET_PROMOTIONS_REQUEST';
export const GET_PROMOTIONS_SUCCESS = 'GET_PROMOTIONS_SUCCESS';
export const GET_PROMOTIONS_FAIL = 'GET_PROMOTIONS_FAIL';

export const GET_PROMOTION_DETAILS_REQUEST = 'GET_PROMOTION_DETAILS_REQUEST';
export const GET_PROMOTION_DETAILS_SUCCESS = 'GET_PROMOTION_DETAILS_SUCCESS';
export const GET_PROMOTION_DETAILS_FAIL = 'GET_PROMOTION_DETAILS_FAIL';
export const GET_PROMOTION_DETAILS_RESET = 'GET_PROMOTION_DETAILS_RESET';